#!/usr/bin/env bash

# PLEASE NOTE: This script has been automatically generated by conda-smithy. Any changes here
# will be lost next time ``conda smithy rerender`` is run. If you would like to make permanent
# changes to this script, consider a proposal to conda-smithy so that other feedstocks can also
# benefit from the improvement.

# -*- mode: jinja-shell -*-

set -xeuo pipefail
export FEEDSTOCK_ROOT="${FEEDSTOCK_ROOT:-/home/conda/feedstock_root}"
# ensure absolute path
FEEDSTOCK_ROOT=$(cd "${FEEDSTOCK_ROOT}"; pwd)
source ${FEEDSTOCK_ROOT}/.scripts/logging_utils.sh


( endgroup "Start Docker" ) 2> /dev/null

( startgroup "Configuring build environment" ) 2> /dev/null

MINIFORGE_HOME=/opt/conda
export PYTHONUNBUFFERED=1
export RECIPE_ROOT="${RECIPE_ROOT:-/home/conda/recipe_root}"
# ensure absolute path
RECIPE_ROOT=$(cd "${RECIPE_ROOT}"; pwd)
export CI_SUPPORT="${FEEDSTOCK_ROOT}/.ci_support"
export CONFIG_FILE="${CI_SUPPORT}/${CONFIG}.yaml"
export PIXI_CACHE_DIR="${MINIFORGE_HOME}"
export RATTLER_CACHE_DIR="${FEEDSTOCK_ROOT}/build_artifacts/pkg_cache"

cat >~/.condarc <<CONDARC

conda-build:
  root-dir: ${FEEDSTOCK_ROOT}/build_artifacts
pkgs_dirs:
  - ${FEEDSTOCK_ROOT}/build_artifacts/pkg_cache
  - ${MINIFORGE_HOME}/pkgs
solver: libmamba

CONDARC

( endgroup "Configuring build environment" ) 2> /dev/null

( startgroup "Provisioning base env with micromamba" ) 2> /dev/null

MAMBA_ROOT_PREFIX=~/.conda
MICROMAMBA_EXE=micromamba

echo Creating environment
mv "${MINIFORGE_HOME}"/conda-meta/history "${MINIFORGE_HOME}"/conda-meta/history.$(date +%Y-%m-%d-%H-%M-%S)
echo > "${MINIFORGE_HOME}"/conda-meta/history
"${MICROMAMBA_EXE}" install --yes --root-prefix "${MAMBA_ROOT_PREFIX}" --prefix "${MINIFORGE_HOME}" \
    --override-channels --channel conda-forge --strict-channel-priority \
    pip  python=3.14 conda-build conda-forge-ci-setup=4 "conda-build>=26.3"

( endgroup "Provisioning base env with micromamba" ) 2> /dev/null

( startgroup "Configuring conda" ) 2> /dev/null
export CONDA_LIBMAMBA_SOLVER_NO_CHANNELS_FROM_INSTALLED=1



# Set basic configuration
echo Setting up configuration
setup_conda_rc "${FEEDSTOCK_ROOT}" "${RECIPE_ROOT}" "${CONFIG_FILE}"

# Linux-specific setup
echo Running build setup
source run_conda_forge_build_setup





( endgroup "Configuring conda" ) 2> /dev/null

# make the build number clobber
make_build_number "${FEEDSTOCK_ROOT}" "${RECIPE_ROOT}" "${CONFIG_FILE}"

if [[ -f "${FEEDSTOCK_ROOT}/LICENSE.txt" ]]; then
    echo Copying feedstock license
    cp "${FEEDSTOCK_ROOT}/LICENSE.txt" "${RECIPE_ROOT}/recipe-scripts-license.txt"
fi

if [[ "${BUILD_WITH_CONDA_DEBUG:-0}" == 1 ]]; then
    # differences between conda-build vs. rattler-build
    #   - 1 step (conda debug + manually open shell) vs. 2 step (rb debug {setup, shell})
    #   - recipe is positional vs. --recipe "${RECIPE_ROOT}"
    #   - --output-id vs. --output-name
    #   - --clobber-file vs. none
    #   - none vs. --target-platform
    CONDA_SUBDIR="${BUILD_PLATFORM}" conda debug \
        "${RECIPE_ROOT}" \
        -m "${CONFIG_FILE}" \
        ${EXTRA_CB_OPTIONS:-} \
        ${BUILD_OUTPUT_ID:+--output-id "${BUILD_OUTPUT_ID}"} \
        --clobber-file "${CI_SUPPORT}/clobber_${CONFIG}.yaml"

    # Drop into an interactive shell
    /bin/bash
fi

# Build the recipe
echo Building recipe

# differences between conda-build vs. rattler-build
#   - recipe is positional vs. --recipe "${RECIPE_ROOT}"
#   - --suppress-variables vs. none
#   - --clobber-file vs. none
#   - none vs. --target-platform
#   - --extra-meta a=b c=d vs. --extra-meta a=b --extra-meta c=d

CONDA_SUBDIR="${BUILD_PLATFORM}" conda-build \
    "${RECIPE_ROOT}" \
    -m "${CONFIG_FILE}" \
    ${EXTRA_CB_OPTIONS:-} \
    --suppress-variables \
    --clobber-file "${CI_SUPPORT}/clobber_${CONFIG}.yaml" \
    --extra-meta flow_run_id="${flow_run_id:-}" remote_url="${remote_url:-}" sha="${sha:-}"

( startgroup "Inspecting artifacts" ) 2> /dev/null

# inspect_artifacts was only added in conda-forge-ci-setup 4.9.4
command -v inspect_artifacts >/dev/null 2>&1 && inspect_artifacts --recipe-dir "${RECIPE_ROOT}" -m "${CONFIG_FILE}" || echo "inspect_artifacts needs conda-forge-ci-setup >=4.9.4"

( endgroup "Inspecting artifacts" ) 2> /dev/null
( startgroup "Validating outputs" ) 2> /dev/null
validate_recipe_outputs "${FEEDSTOCK_NAME}"
( endgroup "Validating outputs" ) 2> /dev/null

if [[ "${UPLOAD_PACKAGES}" != "False" ]] && [[ "${IS_PR_BUILD}" == "False" ]]; then
    ( startgroup "Uploading packages" ) 2> /dev/null
    upload_package --validate --feedstock-name="${FEEDSTOCK_NAME}"  "${FEEDSTOCK_ROOT}" "${RECIPE_ROOT}" "${CONFIG_FILE}"
    ( endgroup "Uploading packages" ) 2> /dev/null
fi

( startgroup "Leaving the Docker container" ) 2> /dev/null

touch "${FEEDSTOCK_ROOT}/build_artifacts/conda-forge-build-done-${CONFIG}"
