#!/usr/bin/env bash

# PLEASE NOTE: This script has been automatically generated by conda-smithy. Any changes here
# will be lost next time ``conda smithy rerender`` is run. If you would like to make permanent
# changes to this script, consider a proposal to conda-smithy so that other feedstocks can also
# benefit from the improvement.

# -*- mode: jinja-shell -*-

set -xeuo pipefail
export FEEDSTOCK_ROOT="${FEEDSTOCK_ROOT:-/home/conda/feedstock_root}"
# ensure absolute path
FEEDSTOCK_ROOT=$(cd "${FEEDSTOCK_ROOT}"; pwd)
source ${FEEDSTOCK_ROOT}/.scripts/logging_utils.sh

RUN_SCRIPT=$1
case ${RUN_SCRIPT} in
    build_common.sh|upload.sh)
        ;;
    *)
        echo "Unknown script requested: ${RUN_SCRIPT}"
        exit 1
        ;;
esac


( endgroup "Start Docker" ) 2> /dev/null

( startgroup "Configuring build environment" ) 2> /dev/null

MINIFORGE_HOME=/opt/conda
export PYTHONUNBUFFERED=1
export RECIPE_ROOT="${RECIPE_ROOT:-/home/conda/recipe_root}"
# ensure absolute path
RECIPE_ROOT=$(cd "${RECIPE_ROOT}"; pwd)
export CI_SUPPORT="${FEEDSTOCK_ROOT}/.ci_support"
export CONFIG_FILE="${CI_SUPPORT}/${CONFIG}.yaml"
export PIXI_CACHE_DIR="${MINIFORGE_HOME}"
export RATTLER_CACHE_DIR="${FEEDSTOCK_ROOT}/build_artifacts/pkg_cache"

cat >~/.condarc <<CONDARC

conda-build:
  root-dir: ${FEEDSTOCK_ROOT}/build_artifacts
pkgs_dirs:
  - ${FEEDSTOCK_ROOT}/build_artifacts/pkg_cache
  - ${MINIFORGE_HOME}/pkgs
solver: libmamba

CONDARC

( endgroup "Configuring build environment" ) 2> /dev/null

( startgroup "Provisioning base env with micromamba" ) 2> /dev/null

MAMBA_ROOT_PREFIX=~/.conda
MICROMAMBA_EXE=micromamba

echo Creating environment
mv "${MINIFORGE_HOME}"/conda-meta/history "${MINIFORGE_HOME}"/conda-meta/history.$(date +%Y-%m-%d-%H-%M-%S)
echo > "${MINIFORGE_HOME}"/conda-meta/history
"${MICROMAMBA_EXE}" install --yes --root-prefix "${MAMBA_ROOT_PREFIX}" --prefix "${MINIFORGE_HOME}" \
    --override-channels --channel conda-forge --strict-channel-priority \
    pip  rattler-build conda-forge-ci-setup=4 "conda-build>=26.3"

( endgroup "Provisioning base env with micromamba" ) 2> /dev/null

( startgroup "Configuring conda" ) 2> /dev/null
export CONDA_LIBMAMBA_SOLVER_NO_CHANNELS_FROM_INSTALLED=1



# Set basic configuration
echo Setting up configuration
setup_conda_rc "${FEEDSTOCK_ROOT}" "${RECIPE_ROOT}" "${CONFIG_FILE}"

# Linux-specific setup
echo Running build setup
source run_conda_forge_build_setup





( endgroup "Configuring conda" ) 2> /dev/null

source "${FEEDSTOCK_ROOT}/.scripts/${RUN_SCRIPT}"

( startgroup "Leaving the Docker container" ) 2> /dev/null

touch "${FEEDSTOCK_ROOT}/build_artifacts/conda-forge-build-done-${CONFIG}"
