# PLEASE NOTE: This script has been automatically generated by conda-smithy. Any changes here
# will be lost next time ``conda smithy rerender`` is run. If you would like to make permanent
# changes to this script, consider a proposal to conda-smithy so that other feedstocks can also
# benefit from the improvement.

# This file is intended to be sourced by a runner script.

# -*- mode: jinja-shell -*-

if [[ -f "${FEEDSTOCK_ROOT}/LICENSE.txt" ]]; then
    echo Copying feedstock license
    cp "${FEEDSTOCK_ROOT}/LICENSE.txt" "${RECIPE_ROOT}/recipe-scripts-license.txt"
fi

if [[ "${BUILD_WITH_CONDA_DEBUG:-0}" == 1 ]]; then
    # differences between conda-build vs. rattler-build
    #   - 1 step (conda debug + manually open shell) vs. 2 step (rb debug {setup, shell})
    #   - recipe is positional vs. --recipe "${RECIPE_ROOT}"
    #   - --output-id vs. --output-name
    #   - --clobber-file vs. none
    #   - none vs. --target-platform
    export CONDA_BLD_PATH="${CONDA_BLD_PATH:-${FEEDSTOCK_ROOT}/build_artifacts}"
    rattler-build debug setup \
        --recipe "${RECIPE_ROOT}" \
        -m "${CONFIG_FILE}" \
        ${EXTRA_CB_OPTIONS:-} \
        ${BUILD_OUTPUT_ID:+--output-name "${BUILD_OUTPUT_ID}"} \
        --build-platform "${BUILD_PLATFORM}" \
        --target-platform "${HOST_PLATFORM}"

    rattler-build debug shell
    exit 0
fi

# Build the recipe
echo Building recipe

# differences between conda-build vs. rattler-build
#   - recipe is positional vs. --recipe "${RECIPE_ROOT}"
#   - --suppress-variables vs. none
#   - --clobber-file vs. none
#   - none vs. --target-platform
#   - --extra-meta a=b c=d vs. --extra-meta a=b --extra-meta c=d

 \
    --recipe "${RECIPE_ROOT}" \
    -m "${CONFIG_FILE}" \
    ${EXTRA_CB_OPTIONS:-} \
    --build-platform "${BUILD_PLATFORM}" \
    --target-platform "${HOST_PLATFORM}" \
    --extra-meta flow_run_id="${flow_run_id:-}" \
    --extra-meta remote_url="${remote_url:-}" \
    --extra-meta sha="${sha:-}"

( startgroup "Inspecting artifacts" ) 2> /dev/null

# inspect_artifacts was only added in conda-forge-ci-setup 4.9.4
command -v inspect_artifacts >/dev/null 2>&1 && inspect_artifacts --recipe-dir "${RECIPE_ROOT}" -m "${CONFIG_FILE}" || echo "inspect_artifacts needs conda-forge-ci-setup >=4.9.4"

( endgroup "Inspecting artifacts" ) 2> /dev/null
