#!/usr/bin/env bash

# PLEASE NOTE: This script has been automatically generated by conda-smithy. Any changes here
# will be lost next time ``conda smithy rerender`` is run. If you would like to make permanent
# changes to this script, consider a proposal to conda-smithy so that other feedstocks can also
# benefit from the improvement.

# -*- mode: jinja-shell -*-

set -xeuo pipefail
export FEEDSTOCK_ROOT=${PWD}
source ${FEEDSTOCK_ROOT}/.scripts/logging_utils.sh


( startgroup "Configuring build environment" ) 2> /dev/null

MINIFORGE_HOME="${MINIFORGE_HOME:-${HOME}/miniforge3}"
MINIFORGE_HOME="${MINIFORGE_HOME%/}" # remove trailing slash
export CONDA_BLD_PATH="${CONDA_BLD_PATH:-${MINIFORGE_HOME}/conda-bld}"
export RECIPE_ROOT="recipe"
# ensure absolute path
RECIPE_ROOT=$(cd "${RECIPE_ROOT}"; pwd)
export CI_SUPPORT="${FEEDSTOCK_ROOT}/.ci_support"
export CONFIG_FILE="${CI_SUPPORT}/${CONFIG}.yaml"
export PIXI_CACHE_DIR="${MINIFORGE_HOME}"
export RATTLER_CACHE_DIR="${CONDA_BLD_PATH}/pkg_cache"

( endgroup "Configuring build environment" ) 2> /dev/null

( startgroup "Provisioning base env with pixi" ) 2> /dev/null

echo Installing pixi
curl -fsSL https://pixi.sh/install.sh | bash
export PATH="~/.pixi/bin:$PATH"

pushd "${FEEDSTOCK_ROOT}"
echo Installing environment
mkdir -p "${MINIFORGE_HOME}"
arch=$(uname -m)
if [[ "$arch" == "x86_64" ]]; then
  arch="64"
fi
PIXI_ENV=build
sed -i.bak "s/platforms = .*/platforms = [\"osx-${arch}\"]/" pixi.toml
pixi install --environment "${PIXI_ENV}"
pixi list --environment "${PIXI_ENV}"

echo Activating environment
eval "$(pixi shell-hook --environment "${PIXI_ENV}")"
mv pixi.toml.bak pixi.toml
popd

( endgroup "Provisioning base env with pixi" ) 2> /dev/null

( startgroup "Configuring conda" ) 2> /dev/null

# Activate the base conda environment
# Configure the solver
export CONDA_SOLVER="libmamba"
export CONDA_LIBMAMBA_SOLVER_NO_CHANNELS_FROM_INSTALLED=1



# Set basic configuration
echo Setting up configuration
setup_conda_rc "${FEEDSTOCK_ROOT}" "${RECIPE_ROOT}" "${CONFIG_FILE}"

# macOS-specific setup
if [[ "${CI:-}" != "" ]]; then
    mangle_compiler "${FEEDSTOCK_ROOT}" "${RECIPE_ROOT}" "${CONFIG_FILE}"
fi

if [[ "${CI:-}" != "" ]]; then
    echo "Mangling homebrew in the CI to avoid conflicts."
    /usr/bin/sudo mangle_homebrew
    /usr/bin/sudo -k
else
    echo "Not mangling homebrew as we are not running in CI"
fi

if [[ "${sha:-}" == "" ]]; then
    sha=$(git rev-parse HEAD)
fi

if [[ "${OSX_SDK_DIR:-}" == "" ]]; then
    if [[ "${CI:-}" == "" ]]; then
        echo "Please set OSX_SDK_DIR to a directory where SDKs can be downloaded to. Aborting"
        exit 1
    else
        export OSX_SDK_DIR=/opt/conda-sdks
        /usr/bin/sudo mkdir -p "${OSX_SDK_DIR}"
        /usr/bin/sudo chown "${USER}" "${OSX_SDK_DIR}"
    fi
else
    if tmpf=$(mktemp "$OSX_SDK_DIR"/tmp.XXXXXXXX 2>/dev/null); then
        rm -f "$tmpf"
        echo "OSX_SDK_DIR is writeable without sudo, continuing"
    else
        echo "User-provided OSX_SDK_DIR is not writeable for current user! Aborting"
        exit 1
    fi
fi

echo Running build setup
source run_conda_forge_build_setup



( endgroup "Configuring conda" ) 2> /dev/null

if [[ -f "${FEEDSTOCK_ROOT}/LICENSE.txt" ]]; then
    echo Copying feedstock license
    cp "${FEEDSTOCK_ROOT}/LICENSE.txt" "${RECIPE_ROOT}/recipe-scripts-license.txt"
fi

if [[ "${BUILD_WITH_CONDA_DEBUG:-0}" == 1 ]]; then
    # differences between conda-build vs. rattler-build
    #   - 1 step (conda debug + manually open shell) vs. 2 step (rb debug {setup, shell})
    #   - recipe is positional vs. --recipe "${RECIPE_ROOT}"
    #   - --output-id vs. --output-name
    #   - --clobber-file vs. none
    #   - none vs. --target-platform
    export CONDA_BLD_PATH="${CONDA_BLD_PATH:-${FEEDSTOCK_ROOT}/build_artifacts}"
    rattler-build debug setup \
        --recipe "${RECIPE_ROOT}" \
        -m "${CONFIG_FILE}" \
        ${EXTRA_CB_OPTIONS:-} \
        ${BUILD_OUTPUT_ID:+--output-name "${BUILD_OUTPUT_ID}"} \
        --build-platform "${BUILD_PLATFORM}" \
        --target-platform "${HOST_PLATFORM}"

    rattler-build debug shell
    exit 0
fi

# Build the recipe
echo Building recipe

# differences between conda-build vs. rattler-build
#   - recipe is positional vs. --recipe "${RECIPE_ROOT}"
#   - --suppress-variables vs. none
#   - --clobber-file vs. none
#   - none vs. --target-platform
#   - --extra-meta a=b c=d vs. --extra-meta a=b --extra-meta c=d

rattler-build build \
    --recipe "${RECIPE_ROOT}" \
    -m "${CONFIG_FILE}" \
    ${EXTRA_CB_OPTIONS:-} \
    --build-platform "${BUILD_PLATFORM}" \
    --target-platform "${HOST_PLATFORM}" \
    --extra-meta flow_run_id="${flow_run_id:-}" \
    --extra-meta remote_url="${remote_url:-}" \
    --extra-meta sha="${sha:-}"

( startgroup "Inspecting artifacts" ) 2> /dev/null

# inspect_artifacts was only added in conda-forge-ci-setup 4.9.4
command -v inspect_artifacts >/dev/null 2>&1 && inspect_artifacts --recipe-dir "${RECIPE_ROOT}" -m "${CONFIG_FILE}" || echo "inspect_artifacts needs conda-forge-ci-setup >=4.9.4"

( endgroup "Inspecting artifacts" ) 2> /dev/null
( startgroup "Validating outputs" ) 2> /dev/null
validate_recipe_outputs "${FEEDSTOCK_NAME}"
( endgroup "Validating outputs" ) 2> /dev/null

if [[ "${UPLOAD_PACKAGES}" != "False" ]] && [[ "${IS_PR_BUILD}" == "False" ]]; then
    ( startgroup "Uploading packages" ) 2> /dev/null
    upload_package --validate --feedstock-name="${FEEDSTOCK_NAME}"  "${FEEDSTOCK_ROOT}" "${RECIPE_ROOT}" "${CONFIG_FILE}"
    ( endgroup "Uploading packages" ) 2> /dev/null
fi
